import type { EventItem, CategoryInfo, Booking, NotificationItem } from './types';

export const categories: CategoryInfo[] = [
  { name: 'Concerts', icon: 'Music', gradient: 'from-purple-500 to-pink-500', count: 128 },
  { name: 'Tech', icon: 'Cpu', gradient: 'from-blue-500 to-cyan-500', count: 94 },
  { name: 'Workshops', icon: 'Palette', gradient: 'from-orange-500 to-amber-500', count: 67 },
  { name: 'Sports', icon: 'Trophy', gradient: 'from-green-500 to-emerald-500', count: 52 },
  { name: 'Weddings', icon: 'Heart', gradient: 'from-rose-500 to-pink-500', count: 43 },
  { name: 'College', icon: 'GraduationCap', gradient: 'from-indigo-500 to-purple-500', count: 78 },
  { name: 'Business', icon: 'Briefcase', gradient: 'from-slate-600 to-slate-800', count: 61 },
  { name: 'Cultural', icon: 'Theater', gradient: 'from-amber-500 to-red-500', count: 39 },
  { name: 'Festivals', icon: 'PartyPopper', gradient: 'from-fuchsia-500 to-purple-500', count: 85 },
];

export const events: EventItem[] = [
  {
    id: 'evt-001',
    title: 'Tech Conference 2026',
    category: 'Tech',
    image: 'https://images.pexels.com/photos/9275222/pexels-photo-9275222.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    date: '2026-09-18',
    time: '10:00 AM – 6:00 PM',
    endDate: '2026-09-19',
    venue: 'Hyderabad International Convention Centre',
    city: 'Hyderabad',
    rating: 4.8,
    reviews: 1240,
    startingPrice: 999,
    attendees: 2400,
    organizer: 'TechCorp India',
    organizerLogo: 'TC',
    description: 'The premier technology conference bringing together industry leaders, innovators, and developers for two days of keynotes, workshops, and networking. Explore the future of AI, Web3, cloud infrastructure, and more.',
    tags: ['AI', 'Web3', 'Cloud', 'Networking', 'Startup'],
    tickets: [
      { id: 't1', name: 'General', price: 999, perks: ['Event access', 'Lunch included', 'Certificate of attendance'] },
      { id: 't2', name: 'VIP', price: 2999, perks: ['Priority seating', 'VIP lounge access', 'Dinner with speakers', 'Exclusive swag kit', 'Certificate of attendance'], badge: 'Popular' },
      { id: 't3', name: 'Student', price: 499, perks: ['Event access', 'Student lunch', 'Workshop materials'], badge: 'Best Value' },
    ],
    featured: true,
    lat: 17.4435,
    lng: 78.3833,
  },
  {
    id: 'evt-002',
    title: 'Midnight Echoes Live Concert',
    category: 'Concerts',
    image: 'https://images.pexels.com/photos/761543/pexels-photo-761543.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    date: '2026-09-25',
    time: '7:00 PM – 11:00 PM',
    endDate: '2026-09-25',
    venue: 'Jio World Garden',
    city: 'Mumbai',
    rating: 4.9,
    reviews: 3400,
    startingPrice: 1499,
    attendees: 5200,
    organizer: 'LiveNation India',
    organizerLogo: 'LN',
    description: 'An electrifying night of live music featuring top indie and mainstream artists. Experience stunning visuals, immersive sound, and unforgettable performances under the stars.',
    tags: ['Live Music', 'Indie', 'Electronic', 'Night'],
    tickets: [
      { id: 't1', name: 'Early Bird', price: 1499, perks: ['Standing access', 'Food court entry'], badge: 'Selling Fast' },
      { id: 't2', name: 'General', price: 2499, perks: ['Standing access', 'Food court entry', 'Merchandise kit'] },
      { id: 't3', name: 'VIP Pit', price: 4999, perks: ['Front-row pit access', 'Backstage tour', 'VIP bar', 'Artist meet & greet', 'Premium merchandise'], badge: 'Premium' },
    ],
    featured: true,
    lat: 19.0596,
    lng: 72.8295,
  },
  {
    id: 'evt-003',
    title: 'Grand Wedding Expo 2026',
    category: 'Weddings',
    image: 'https://images.pexels.com/photos/29040917/pexels-photo-29040917.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    date: '2026-10-05',
    time: '11:00 AM – 7:00 PM',
    endDate: '2026-10-06',
    venue: 'The Leela Palace',
    city: 'Bengaluru',
    rating: 4.7,
    reviews: 560,
    startingPrice: 799,
    attendees: 1800,
    organizer: 'Vows & Venues',
    organizerLogo: 'VV',
    description: 'Discover the finest wedding planners, decorators, caterers, photographers, and venues all under one roof. A two-day showcase of the latest wedding trends with live demos and exclusive booking offers.',
    tags: ['Wedding', 'Lifestyle', 'Planning', 'Decor'],
    tickets: [
      { id: 't1', name: 'Visitor', price: 799, perks: ['Expo entry', 'Welcome kit', 'Vendor directory'] },
      { id: 't2', name: 'Couple Pass', price: 1499, perks: ['Expo entry for two', 'Priority vendor meetings', 'Welcome kit', 'Free consultation voucher'], badge: 'Couples' },
    ],
    lat: 12.9719,
    lng: 77.5937,
  },
  {
    id: 'evt-004',
    title: 'Champions League Cricket Finals',
    category: 'Sports',
    image: 'https://images.pexels.com/photos/30651230/pexels-photo-30651230.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    date: '2026-09-30',
    time: '6:00 PM – 10:00 PM',
    endDate: '2026-09-30',
    venue: 'Narendra Modi Stadium',
    city: 'Ahmedabad',
    rating: 4.9,
    reviews: 8900,
    startingPrice: 1999,
    attendees: 98000,
    organizer: 'Sports Authority',
    organizerLogo: 'SA',
    description: 'Witness the ultimate cricket showdown as the top two teams battle for the championship title in the world\'s largest cricket stadium. An evening of thrilling sports, entertainment, and unforgettable moments.',
    tags: ['Cricket', 'Finals', 'Stadium', 'Live'],
    tickets: [
      { id: 't1', name: 'Upper Tier', price: 1999, perks: ['Stadium entry', 'Snack voucher'] },
      { id: 't2', name: 'Pavilion', price: 5999, perks: ['Pavilion seating', 'Dinner included', 'Parking pass'], badge: 'Premium' },
      { id: 't3', name: 'Corporate Box', price: 14999, perks: ['Air-conditioned box', 'Full catering', 'Open bar', 'Dedicated host', 'VIP parking'], badge: 'Luxury' },
    ],
    featured: true,
    lat: 23.0837,
    lng: 72.5797,
  },
  {
    id: 'evt-005',
    title: 'Creative Arts Workshop Series',
    category: 'Workshops',
    image: 'https://images.pexels.com/photos/39205380/pexels-photo-39205380.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    date: '2026-09-15',
    time: '2:00 PM – 5:00 PM',
    endDate: '2026-09-15',
    venue: 'Artisan Studio',
    city: 'Pune',
    rating: 4.6,
    reviews: 320,
    startingPrice: 599,
    attendees: 150,
    organizer: 'Artisan Collective',
    organizerLogo: 'AC',
    description: 'A hands-on workshop exploring painting, resin art, and mixed media techniques. Perfect for beginners and intermediate artists. All materials provided. Take home your creations!',
    tags: ['Art', 'Painting', 'Hands-on', 'Beginner-friendly'],
    tickets: [
      { id: 't1', name: 'Single Session', price: 599, perks: ['All materials', 'Take-home artwork', 'Refreshments'] },
      { id: 't2', name: 'Full Series', price: 2499, perks: ['4 workshop sessions', 'All materials', 'Personalized portfolio', 'Certificate', 'Artist toolkit'], badge: 'Best Value' },
    ],
    lat: 18.5204,
    lng: 73.8567,
  },
  {
    id: 'evt-006',
    title: 'Fusion Festival 2026',
    category: 'Festivals',
    image: 'https://images.pexels.com/photos/17373843/pexels-photo-17373843.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    date: '2026-10-12',
    time: '4:00 PM – 12:00 AM',
    endDate: '2026-10-13',
    venue: 'Eco Park Grounds',
    city: 'Kolkata',
    rating: 4.8,
    reviews: 2100,
    startingPrice: 1299,
    attendees: 8500,
    organizer: 'Fusion Entertainment',
    organizerLogo: 'FE',
    description: 'A vibrant celebration of music, food, and culture. Featuring multiple stages with live performances, food trucks from across the country, art installations, and a spectacular fireworks finale.',
    tags: ['Festival', 'Food', 'Music', 'Culture', 'Family'],
    tickets: [
      { id: 't1', name: 'Day Pass', price: 1299, perks: ['Full-day entry', 'Food court access'] },
      { id: 't2', name: 'Weekend Pass', price: 3499, perks: ['Two-day entry', 'Food court access', 'Camping spot', 'Festival merchandise'], badge: 'Weekend' },
      { id: 't3', name: 'VIP Experience', price: 7999, perks: ['VIP viewing decks', 'Private bar', 'Backstage access', 'Gourmet dining', 'Festival merchandise', 'Express entry'], badge: 'VIP' },
    ],
    featured: true,
    lat: 22.5726,
    lng: 88.3639,
  },
  {
    id: 'evt-007',
    title: 'Business Leadership Summit',
    category: 'Business',
    image: 'https://images.pexels.com/photos/8761650/pexels-photo-8761650.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    date: '2026-09-22',
    time: '9:00 AM – 5:00 PM',
    endDate: '2026-09-22',
    venue: 'ITC Grand Chola',
    city: 'Chennai',
    rating: 4.7,
    reviews: 680,
    startingPrice: 4999,
    attendees: 800,
    organizer: 'Forbes India',
    organizerLogo: 'FI',
    description: 'An exclusive summit for C-suite executives, founders, and business leaders. Keynotes from industry titans, panel discussions on market trends, and curated networking sessions.',
    tags: ['Leadership', 'Networking', 'C-Suite', 'Strategy'],
    tickets: [
      { id: 't1', name: 'Executive', price: 4999, perks: ['Summit access', 'Networking lunch', 'Delegate kit'] },
      { id: 't2', name: 'VIP Executive', price: 12999, perks: ['Priority seating', 'Private networking dinner', 'Delegate kit', 'Post-event report', '1-on-1 meetings'], badge: 'VIP' },
    ],
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    id: 'evt-008',
    title: 'Cultural Heritage Night',
    category: 'Cultural',
    image: 'https://images.pexels.com/photos/11787164/pexels-photo-11787164.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    date: '2026-10-08',
    time: '6:30 PM – 9:30 PM',
    endDate: '2026-10-08',
    venue: 'Ravindra Bharathi',
    city: 'Hyderabad',
    rating: 4.8,
    reviews: 450,
    startingPrice: 399,
    attendees: 600,
    organizer: 'Heritage Arts Foundation',
    organizerLogo: 'HF',
    description: 'An enchanting evening of classical dance, music, and theatrical performances celebrating India\'s rich cultural heritage. Featuring award-winning artists and emerging talent.',
    tags: ['Dance', 'Classical', 'Heritage', 'Theatre'],
    tickets: [
      { id: 't1', name: 'Balcony', price: 399, perks: ['Show entry', 'Program booklet'] },
      { id: 't2', name: 'Premium', price: 999, perks: ['Premium seating', 'Program booklet', 'Tea & snacks'] },
      { id: 't3', name: 'Patron', price: 2999, perks: ['Front-row seating', 'Backstage meet', 'Dinner with artists', 'Signed memorabilia'], badge: 'Patron' },
    ],
    lat: 17.385,
    lng: 78.4867,
  },
  {
    id: 'evt-009',
    title: 'Campus Innovation Fest',
    category: 'College',
    image: 'https://images.pexels.com/photos/35997307/pexels-photo-35997307.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    date: '2026-09-28',
    time: '9:00 AM – 8:00 PM',
    endDate: '2026-09-29',
    venue: 'IIT Bombay Campus',
    city: 'Mumbai',
    rating: 4.6,
    reviews: 1200,
    startingPrice: 299,
    attendees: 3500,
    organizer: 'IIT Bombay',
    organizerLogo: 'IIT',
    description: 'A two-day inter-college festival featuring hackathons, robotics competitions, startup pitches, cultural performances, and celebrity appearances. The ultimate college experience!',
    tags: ['Hackathon', 'Robotics', 'Startup', 'College', 'Competition'],
    tickets: [
      { id: 't1', name: 'Student Pass', price: 299, perks: ['Festival entry', 'Workshop access', 'Food coupons'], badge: 'Students' },
      { id: 't2', name: 'Visitor Pass', price: 599, perks: ['Festival entry', 'Food coupons', 'Event merchandise'] },
    ],
    lat: 19.1334,
    lng: 72.9133,
  },
];

export const bookings: Booking[] = [
  {
    id: 'EVT-82931',
    eventId: 'evt-001',
    eventTitle: 'Tech Conference 2026',
    eventImage: 'https://images.pexels.com/photos/9275222/pexels-photo-9275222.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    eventDate: '2026-09-18',
    venue: 'Hyderabad International Convention Centre',
    ticketType: 'VIP',
    quantity: 2,
    total: 5998,
    status: 'upcoming',
    bookingDate: '2026-08-15',
  },
  {
    id: 'EVT-82745',
    eventId: 'evt-005',
    eventTitle: 'Creative Arts Workshop Series',
    eventImage: 'https://images.pexels.com/photos/39205380/pexels-photo-39205380.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    eventDate: '2026-09-15',
    venue: 'Artisan Studio, Pune',
    ticketType: 'Full Series',
    quantity: 1,
    total: 2499,
    status: 'upcoming',
    bookingDate: '2026-08-20',
  },
  {
    id: 'EVT-82102',
    eventId: 'evt-002',
    eventTitle: 'Midnight Echoes Live Concert',
    eventImage: 'https://images.pexels.com/photos/761543/pexels-photo-761543.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    eventDate: '2026-08-10',
    venue: 'Jio World Garden, Mumbai',
    ticketType: 'VIP Pit',
    quantity: 2,
    total: 9998,
    status: 'attended',
    bookingDate: '2026-07-01',
  },
  {
    id: 'EVT-81998',
    eventId: 'evt-006',
    eventTitle: 'Fusion Festival 2026',
    eventImage: 'https://images.pexels.com/photos/17373843/pexels-photo-17373843.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    eventDate: '2026-07-20',
    venue: 'Eco Park Grounds, Kolkata',
    ticketType: 'Weekend Pass',
    quantity: 3,
    total: 10497,
    status: 'attended',
    bookingDate: '2026-06-15',
  },
  {
    id: 'EVT-81877',
    eventId: 'evt-008',
    eventTitle: 'Cultural Heritage Night',
    eventImage: 'https://images.pexels.com/photos/11787164/pexels-photo-11787164.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    eventDate: '2026-06-08',
    venue: 'Ravindra Bharathi, Hyderabad',
    ticketType: 'Premium',
    quantity: 2,
    total: 1998,
    status: 'attended',
    bookingDate: '2026-05-20',
  },
];

export const notifications: NotificationItem[] = [
  { id: 'n1', type: 'reminder', title: 'Your event starts tomorrow', message: 'Tech Conference 2026 at Hyderabad International Convention Centre', time: '2h ago', read: false },
  { id: 'n2', type: 'payment', title: 'Payment received', message: '₹5,998 for Tech Conference 2026 VIP tickets', time: '5h ago', read: false },
  { id: 'n3', type: 'booking', title: 'New booking confirmed', message: 'Creative Arts Workshop Series — Full Series pass', time: '1d ago', read: false },
  { id: 'n4', type: 'social', title: 'Rahul completed Stage Setup', message: 'Task moved to Completed in Tech Conference 2026', time: '2d ago', read: true },
  { id: 'n5', type: 'update', title: 'Event schedule updated', message: 'Tech Conference 2026 keynote moved to 11:00 AM', time: '3d ago', read: true },
];

export const stats = {
  totalBookings: 24,
  savedEvents: 12,
  eventsAttended: 18,
  totalSpent: 24800,
};

export const dashboardStats = {
  revenue: 482000,
  ticketsSold: 2481,
  attendance: 87,
  activeEvents: 8,
};

export const avatars = [
  'https://images.pexels.com/photos/5308640/pexels-photo-5308640.jpeg?auto=compress&cs=tinysrgb&h=100&w=100',
  'https://images.pexels.com/photos/37273005/pexels-photo-37273005.png?auto=compress&cs=tinysrgb&h=100&w=100',
  'https://images.pexels.com/photos/14950779/pexels-photo-14950779.jpeg?auto=compress&cs=tinysrgb&h=100&w=100',
  'https://images.pexels.com/photos/5197205/pexels-photo-5197205.jpeg?auto=compress&cs=tinysrgb&h=100&w=100',
];
